algorithm: fullysupervised
save_dir: ./saved_models/classic_cv
# save_name: fullysupervised_domainnet_1260_0
resume: True
# load_path: ./saved_models/classic_cv/fullysupervised_domainnet_1260_0/latest_model.pth
overwrite: True
use_pretrain: True
use_tensorboard: True
use_wandb: False
epoch: 150
num_train_iter: 5100
num_eval_iter: 102
num_log_iter: 20
num_labels: 1260
batch_size: 32
eval_batch_size: 256
ema_m: 0.999
crop_ratio: 0.875
img_size: 256
optim: SGD
lr: 5e-4
momentum: 0.9
weight_decay: 1e-4
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet50
net_from_torch: True
data_dir: ./data
dataset: officehome
train_sampler: RandomSampler
num_classes: 65
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10023
dist_backend: nccl
gpu: 0
