algorithm: fullysupervised
save_dir: ./saved_models/classic_cv
# save_name: fullysupervised_domainnet_1260_0
resume: True
# load_path: ./saved_models/classic_cv/fullysupervised_domainnet_1260_0/latest_model.pth
overwrite: True
use_pretrain: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 17000
num_eval_iter: 512
num_log_iter: 50
num_labels: 1260
batch_size: 32
eval_batch_size: 256
ema_m: 0.999
crop_ratio: 0.875
img_size: 256
optim: AdamW
lr: 5e-4
layer_decay: 0.65
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch16_224
net_from_torch: False
data_dir: ./data
dataset: domainnet
train_sampler: RandomSampler
num_classes: 126
num_workers: 1
# seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10023
dist_backend: nccl
gpu: 0
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch16_224_mlp_im_1k_224.pth
num_warmup_iter: 2048